#!/bin/bash
#
# $Id$
#
### BEGIN INIT INFO
# Provides: dnsqltraq
# Short-Description: This daemon live parses and correlates the dnsmasq log
# Description: This tool corrlates the output of dnsmasq into a MySQL db record
#              per lookup per client, tracking the info source among:
#              "reply"=upstream DNS, "cached", or local filename.
#              Designed to run as a persistent script
### END INIT INFO

# chkconfig: 2345 95 05
# config: /etc/sysconfig/dnsqltraq

# Source function library.
. /etc/init.d/functions

#
# Set local vars
#
# PKG: package name
PKG=dnsqltraq
# prog: package daemon
prog=/usr/local/sbin/${PKG}.sh

#
# Set default options.  Override the defaults and define
# custom options in /etc/sysconfig/logsneak

#
LOCKFILE=/var/lock/subsys/$PKG

[ -f /etc/sysconfig/$PKG ] && . /etc/sysconfig/$PKG


start() {
	echo -n $"Starting $PKG:"

	(setsid $prog &)
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch $LOCKFILE
	echo
}

stop() {
	echo -n $"Stopping $PKG:"

	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f $LOCKFILE
	echo
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
	RETVAL=$?
        ;;
  restart|reload)
        restart
        ;;
  condrestart)
        if status $prog > /dev/null; then
            stop
            start
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 2
esac
exit $RETVAL

